name: Prisma Migrate

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Remove Previous Prisma Client
        run: rm -rf node_modules/.prisma

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Deploy Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
