name: Prisma Migrate

on:
  workflow_dispatch:
  workflow_call:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          DATABASE_DIRECT_URL: ${{ secrets.PROD_DIRECT_URL }}
